name: Remember to bump version & Changelog

on:
  pull_request:

permissions:
  pull-requests: read

jobs:
  check-for-version-bump:
    uses: dgholz/action-check-version-bump/.github/workflows/check_version_bump.yml@main
    secrets: inherit
